# Wraith
# You will need wraith, imagemagick, and phantomsjs or similar.
#
# gem install wraith
# brew install phantomjs
# brew install imagemagick
#
# Take a baseline of the current version
#
# wraith history config.yml
#
# Switch to your feature branch and make changes.
#
# wraith latest config.yml
#
# This should generate a gallery containing diffs of the pages, at
# various resolutions.

#Headless browser option
browser:
  phantomjs: "phantomjs"
  # slimerjs: "slimerjs"

#If you want to have multiple snapping files, set the file name here
# snap_file: "wraith/javascripts/snap.js"

# Type the name of the directory that shots will be stored in
directory: "wraith/shots"
history_dir: "wraith/shots_history"

# Add maximum of 2 domains, key will act as a label
domains:
  dev: "http://localhost:8000"

#Type screen widths below, here are a couple of examples
screen_widths:
  - 320
  - 600
  - 768
  - 1024
  - 1280

# 1. Type page URL paths below, here are a couple of examples
#paths:
#  home: "/"
#  forms: "/forms/"
#  textbox: "/forms/textbox.html"
#  breadcrumb: "/breadcrumb.html"

# 2. OR specify a yml file with all of the urls (wraith can generate this automatically)
imports: "spider.yml"

# (optional) JavaScript file to execute before taking screenshot of every path. Default: nil
before_capture: "wraith/javascripts/wait--phantom.js"

# (optional) Resize to each screen width (efficient), or reload at each screen width (costly). Default: 'reload'
resize_or_reload: "resize"

#Amount of fuzz ImageMagick will use
fuzz: "20%"

#Set the number of days to keep the site spider file
spider_days:
  - 10

#Choose how results are displayed, by default alphanumeric. Different screen widths are always grouped.
#alphanumeric - all paths (with, and without, a difference) are shown, sorted by path
#diffs_first - all paths (with, and without, a difference) are shown, sorted by difference size (largest first)
#diffs_only - only paths with a difference are shown, sorted by difference size (largest first)
mode: diffs_first

# (optional) The maximum acceptable level of difference (in %) between two images before Wraith reports a failure. Default: 0
threshold: 0

# (optional) Choose to run Wraith in verbose mode, for easier debugging. Default: false
verbose: false

# (optional) Color to highlight the image diff. Default: 'blue'
highlight_color: red

# (optional) Parameters to pass to Phantom/Casper command line. Default: '--ignore-ssl-errors=true --ssl-protocol=tlsv1'
phantomjs_options: ""

# (optional) Specify the template (and generated thumbnail sizes) for the gallery output.
gallery:
  template: "slideshow_template" # Examples: 'basic_template' (default), 'slideshow_template'
  thumb_width:  200
  thumb_height: 200
