name: Publish Pages

on: 
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
       
    - uses: actions/setup-python@v2
      with:
        python-version: '3.6.x' 
    
    - uses: actions/cache@v2
      id: node-cache
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-    
    
    - uses: actions/cache@v2
      with:
        path: venv
        key: venv-${{ runner.os }}-${{ hashFiles('**/requirements*.txt') }}
        restore-keys: venv-${{ runner.os }}-

    - name: Install Node version
      shell: bash -l {0}
      run: nvm install
          
    - name: Install Node dependencies
      run: npm install
      if: steps.node-cache.outputs.cache-hit != 'true'

    - run: make generate_pages
    
    - name: Push to gh-pages
      uses: peaceiris/actions-gh-pages@8457ade3d7045b4842e5a10f733d4153b7d05238
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./pages
