name: Test

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      
    
    - uses: actions/setup-python@v2
      with:
        python-version: '3.6.x' 
    
    - uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-    
    
    - uses: actions/cache@v2
      with:
        path: venv
        key: venv-${{ runner.os }}-${{ hashFiles('**/requirements*.txt') }}
        restore-keys: venv-${{ runner.os }}-
          
    - name: Install Node version
      shell: bash -l {0}
      run: nvm install

    - run: npm install    
    - run: make test
    - run: make generate_pages
