name: Test

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      
    - uses: actions/setup-node@v2
      with:
        node-version: 10.x
    
    - uses: actions/setup-python@v2
      with:
        python-version: '3.6.x' 

    - run: npm install    
    - run: make test
    - run: make generate_pages
